name: CD Fake
on:
  workflow_dispatch
jobs:
  deploy-fake:
    runs-on: ubuntu-latest
    environment: Hml
    steps:
      - name: Deploy fake no ambiente
        run: echo "Realizando deploy fake no ambiente ${{ vars.AMBIENTE_DEPLOY }}"
