name: CD Fake
on:
  workflow_dispatch:
jobs:
  deploy-hml-fake:
    uses: fspelling/repo-ambiente/.github/workflows/cd-deploy-fake.yml@main
    with:
        ambiente: Hml
  testes-hml-fake:
    needs: [deploy-hml-fake]
    runs-on: ubuntu-latest
    environment:
      name: Hml
      url: https://hml.devopspro.com.br
    steps:
      - name: Testes fake no ambiente
        run: echo "Realizando testes fake no ambiente ${{ vars.AMBIENTE_DEPLOY }}"
  deploy-prd-fake:
    needs: [testes-hml-fake]
    uses: fspelling/repo-ambiente/.github/workflows/cd-deploy-fake.yml@main
    with:
        ambiente: Prd
